# Generated by Django 5.2.1 on 2025-05-20 06:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JossToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(default="", max_length=150, unique=True),
                ),
                (
                    "refresh_token",
                    models.CharField(default="", max_length=150, unique=True),
                ),
                ("access_token_lifetime", models.IntegerField(default=7)),
                ("refresh_token_lifetime", models.IntegerField(default=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "refreshed_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025,
                            5,
                            20,
                            12,
                            33,
                            44,
                            308418,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("refresh_count", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joss_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
