# Generated by Django 5.2.1 on 2025-05-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="cover_image",
            field=models.ImageField(blank=True, upload_to="media/user/cover_images/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="dob",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="postal_code",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, upload_to="media/user/profile_images/"),
        ),
    ]
